### ISSUE TITLE
Buscar forma de enviar mensajes en el frontend al usuario. 

### ISSUE THREAD

**Issue by JoniValles** [JoniValles/SDI2#3]

**Comment by Ivanpsl** [comment]
Por medio de el método de BeanUser _mostrarError(String msg)_ 
El mensaje se mostrara en la vista en la posición en la que se situe el siguiente código: 
```
	<p:messages id="messagess" showDetail="true" autoUpdate="true"
							closable="true" />
```
Es posible pasarle como parametro el string que corresponde a una variable del fichero de traducciones para dejar el mensaje internacionalizado, si no la encuentra mostrara directamente el String que se le pasa como parametro
